"""create users table

Revision ID: 358afde6f98a
Revises: 
Create Date: 2026-07-08 19:55:54.866533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '358afde6f98a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's email address — primary login identifier"),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Bcrypt hash — NEVER store plaintext passwords'),
    sa.Column('full_name', sa.String(length=100), nullable=False, comment="User's display name"),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Soft delete flag — inactive users cannot log in'),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False, comment='Email verification status'),
    sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False, comment='Admin flag — superusers bypass permission checks'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Account creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
