"""create sessions table

Revision ID: 4798461e2b24
Revises: 358afde6f98a
Create Date: 2026-07-09 20:45:36.951949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4798461e2b24'
down_revision: Union[str, Sequence[str], None] = '358afde6f98a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='The user who owns this session'),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash of the refresh token'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP address (IPv4 or IPv6)'),
    sa.Column('user_agent', sa.String(length=512), nullable=True, comment='Client User-Agent string (browser/device)'),
    sa.Column('is_revoked', sa.Boolean(), server_default='false', nullable=False, comment='Whether this session has been revoked (logged out)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this session was created (login time)'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment="When this session's refresh token expires"),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last time this session was used to refresh'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_refresh_token_hash'), 'sessions', ['refresh_token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_refresh_token_hash'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
