"""
GateKeeper - Database Layer

Provides:
- Async SQLAlchemy engine (connection pool to PostgreSQL)
- Async session factory
- FastAPI dependency for database sessions
- Declarative base for ORM models

Architecture:
    FastAPI route
        │
        ▼
    get_db() dependency (yields AsyncSession)
        │
        ▼
    async_session_factory (creates sessions from the pool)
        │
        ▼
    async_engine (manages the connection pool to PostgreSQL)
        │
        ▼
    PostgreSQL (via asyncpg driver)

Why async?
    GateKeeper is I/O-heavy: database queries, Redis lookups, HTTP calls
    to OAuth providers, email sending. Async lets us serve hundreds of
    concurrent requests without blocking threads.
"""

import logging
from collections.abc import AsyncGenerator

from sqlalchemy import text
from sqlalchemy.ext.asyncio import (
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase

from app.config import get_settings

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Engine & Session Factory
# ---------------------------------------------------------------------------

settings = get_settings()

async_engine = create_async_engine(
    settings.DATABASE_URL,
    # Pool configuration:
    # - pool_size: number of persistent connections kept open
    # - max_overflow: extra connections allowed during traffic spikes
    # - pool_pre_ping: test connections before using them (handles DB restarts)
    pool_size=10,
    max_overflow=20,
    pool_pre_ping=True,
    echo=settings.DEBUG,  # Log SQL queries in debug mode
)

async_session_factory = async_sessionmaker(
    bind=async_engine,
    class_=AsyncSession,
    # Don't expire objects after commit — avoids lazy-load issues in async
    expire_on_commit=False,
)


# ---------------------------------------------------------------------------
# Declarative Base
# ---------------------------------------------------------------------------


class Base(DeclarativeBase):
    """
    Base class for all SQLAlchemy ORM models.

    All models will inherit from this. Alembic uses Base.metadata
    to detect schema changes for autogenerated migrations.
    """

    pass


# ---------------------------------------------------------------------------
# FastAPI Dependency
# ---------------------------------------------------------------------------


async def get_db() -> AsyncGenerator[AsyncSession, None]:
    """
    FastAPI dependency that provides a database session.

    Usage in a route:
        @router.get("/users")
        async def list_users(db: AsyncSession = Depends(get_db)):
            ...

    The session is automatically committed on success and rolled back
    on any exception. It's always closed when the request finishes.
    """
    async with async_session_factory() as session:
        try:
            yield session
            await session.commit()
        except Exception:
            await session.rollback()
            raise


# ---------------------------------------------------------------------------
# Health Check Helper
# ---------------------------------------------------------------------------


async def check_db_connection() -> bool:
    """
    Verify the database is reachable by executing a simple query.
    Used by the /health endpoint.
    """
    try:
        async with async_engine.connect() as conn:
            await conn.execute(text("SELECT 1"))
        return True
    except Exception as e:
        logger.error("Database health check failed: %s", e)
        return False
